/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '17-6-10 下午8:55' with Gradle 2.14
 *
 * @author Administrator, @date 17-6-10 下午8:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
